function alpha_Exp = part3Alpha(Hexp,T_0,L_Rod,volts,amps,u_t,k_an,cp_an,rho_an)
    Q_exp = volts * amps * (1/1000);
    in_to_m = 0.0254;
    radius_Rod = 0.5 * in_to_m; % [m]
    area_Rod = radius_Rod^2 * pi; % [m^2]
    x_0 = (1 + (3/8)) * in_to_m; % m
    X_Position = [
        x_0 ...
        (x_0 + 1*(0.5 * in_to_m)) ...
        (x_0 + 2*(0.5 * in_to_m)) ...
        (x_0 + 3*(0.5 * in_to_m)) ...
        (x_0 + 4*(0.5 * in_to_m)) ...
        (x_0 + 5*(0.5 * in_to_m)) ...
        (x_0 + 6*(0.5 * in_to_m)) ...
        (x_0 + 7*(0.5 * in_to_m)) ...
    ];
    alpha_Exp = (Q_exp / (Hexp  * area_Rod)) / (rho_an * cp_an);

end